### PR TITLE
update bundled pygments to version 2.2.0

### PR DESCRIPTION
**Pull request by smammy**
Took `pygmentize` script and `pygments` dir from PyPI source tarball `Pygments-2.2.0.tar.gz`. Had to change shebang line since macOS doesn't ship a `python2` binary. (And without that, there's no reason to involve `/usr/bin/env` since we know we're shipping on macOS.)

### CODE REVIEW

**Comment by freron** [comment]
Thanks for your time doing this. A few comments:

* I would like to keep the LICENSE file (or an updated version of it).
* I don't see the shebang change you write about. (Unless you mean the same change I, apparently, had made.)
* You changed the `pygmentize` script, but are you sure your changes work? Note that it needs to make sure that the included version of `pygments` is used and not one that might be installed on your system.

Thanks in advance!

**Comment by smammy** [comment]
* Re: the LICENSE file, that wasn't intentional. I'll push a new patch.
* Re: shebang chance, yes, this was the same change you made.
* Re: other changes to `pygmentize` script, that's the code from upstream, but I see your point. I will correct that.

To be honest, I think you probably should not accept a pull request of this sort, since it would be too easy for a contributor to hide malicious code in such a large patch. Would you consider grabbing the updated version from upstream yourself?

**Comment by smammy** [comment]
Here is a more minimal patch made by applying the delta between tags `2.0.2` and `2.2.0` in Pygments mercurial repo to contents of `Support/vendor`.

**Comment by freron** [comment]
I've checked your committed changes to avoid malicious code. Strangely, when I pulled down the 2.2.0 branch (form Bitbucket) then it wasn't exactly identical to your 2.2.0 files. There are minor code differences and some copyright-date differences as well. Maybe they tagged the wrong commit with 2.2.0. Or the tarball is different for some weird reason. I assume you don't have any thoughts on that?

**Comment by smammy** [comment]
Yeah, maybe they tweaked the code before creating the tarball that they submitted to PyPI? but take a look at my updated commit 77085c3, which I generated with:

```bash
hg clone https://bitbucket.org/birkenfeld/pygments-main
git clone git@github.com:smammy/pygments.mmbundle.git
cd pygments.mmbundle/Support/vendor
git checkout -b bundle-pygments-220
hg diff -r 2.0.2 -r 2.2.0 ../../../pygments-main/pygments | patch -p1
git add .
git commit -m 'update bundled pygments to version 2.2.0'
```

**Comment by freron** [comment]
I started over and re-created the vendor folder (as I did it originally). It should be easier to update it in the future. In the process I also added the automatic inclusion of some popular custom styles.

By the way, were you looking for a particular pygments feature/fix when you decided to update it?

I haven't pushed the update to MailMate users yet, but you can try it out directly from github if you like.

Thanks for your help.

**Comment by smammy** [comment]
Thanks, Benny! I specifically wanted [this Perl fix](https://bitbucket.org/birkenfeld/pygments-main/pull-requests/688).

**Pull request closed without merging**
